name: prerelease

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix: 
        node:
          - 18
        platform:
          - ubuntu-latest
    name: '${{matrix.platform}} / Node.js ${{ matrix.node }}'
    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: latest-6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - run: npm whoami
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - run: pnpm install

    - name: run publish
      run: pnpm run publish:prerelease
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}